name: Unit Tests
env:
  DATABASE_URL: ${{ secrets.STAGING_DATABASE_URL }}
  SUPERGOOD_CLIENT_ID: ${{ secrets.STAGING_SUPERGOOD_CLIENT_ID }}
  SUPERGOOD_CLIENT_SECRET: ${{ secrets.STAGING_SUPERGOOD_CLIENT_SECRET }}
  SUPERGOOD_BASE_URL: 'https://staging-api.supergood.ai'
  SUPERGOOD_TELEMETRY_URL: 'https://staging-telemetry.supergood.ai'
  SUPERGOOD_ORGANIZATION_ID: ${{ vars.SUPERGOOD_ORGANIZATION_ID }}
  PYTHONWARNINGS: "default"
on:
  push:
    branches:
      - master
  pull_request:
    branches: [master]
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ".[test]"
          pip install pytest
      - name: Run tests
        run: |
          pytest tests/test_core.py
          pytest tests/test_ignored_domains.py
          pytest tests/test_remote_config.py
          pytest tests/caching/test_location_request_body.py
          pytest tests/caching/test_location_request_headers.py
          pytest tests/redaction/test_no_redaction.py
          pytest tests/redaction/test_redact_all.py
          pytest tests/redaction/test_redact_arrays.py
          pytest tests/redaction/test_redact_by_default.py
          pytest tests/redaction/test_redaction_failures.py
          pytest tests/redaction/test_redaction.py
          pytest tests/redaction/test_top_level_redaction.py
          pytest tests/vendors/test_httpx.py
